import type { UiDictionary } from "@/content/types";

export const ui: UiDictionary = {
  site: {
    name: "TPOWER",
    tagline: "Official TPOWER Partner Website",
    description:
      "Access TPOWER online casino through our official partner website. Register your TPOWER account, log in, explore games, view promotions and get support.",
    footerBlurb: "Official partner website for TPOWER online casino access, registration, login and support.",
    footerLegal: "Official TPOWER Partner Website",
    copyright: "All rights reserved.",
  },
  cta: {
    register: "Register",
    login: "Login",
    registerNow: "Register Now",
    learnMore: "Learn More",
    contactSupport: "Contact Support",
    alreadyAccount: "Already have an account? Login",
    noAccount: "Don't have an account? Register",
    exploreGames: "Explore Games",
    viewPromotions: "View Promotions",
    forgotPassword: "Forgot Password?",
  },
  nav: {
    home: "Home",
    games: "Games",
    promotions: "Promotions",
    payment: "Payment",
    faq: "FAQ",
    support: "Support",
  },
  footer: {
    explore: "Explore",
    account: "Account",
    help: "Help",
    legal: "Legal",
    home: "Home",
    games: "Games",
    promotions: "Promotions",
    payment: "Payment",
    faq: "FAQ",
    support: "Support",
    about: "About",
    contact: "Contact",
    register: "Register",
    login: "Login",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    responsibleGaming: "Responsible Gaming",
    whyTpower: "Why TPOWER",
  },
  forms: {
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    message: "Message",
    password: "Password",
    submitRegister: "Register Now",
    submitLogin: "Login",
    submitContact: "Send Message",
    applicationSubmitted: "Registration Submitted",
    applicationThanks: "Thank you. Our team will follow up with next steps for your TPOWER account.",
    welcomeBack: "Welcome Back",
    loginSubtitle: "Sign in to access your TPOWER account.",
    registerSubtitle: "Create your TPOWER account through this official partner website.",
    becomePartner: "Create Your TPOWER Account",
    contactTitle: "Contact Support",
    contactSubtitle: "Reach the TPOWER support team for registration, login and account questions.",
    contactSent: "Message Sent",
    contactThanks: "Thank you. Our support team will respond as soon as possible.",
    portalLabel: "TPOWER Account Access",
    officialPlatform: "Official TPOWER Partner Website",
    loading: "Submitting…",
    errorRequired: "This field is required.",
  },
  home: {} as import("@/content/en/home").HomeContent,
};
