import type { UiDictionary } from "@/content/types";

export const ui: UiDictionary = {
  site: {
    name: "TPOWER Partner",
    tagline: "Official TPOWER Partner Platform",
    description:
      "TPOWER Partner is the official partner and affiliate platform for TPOWER Casino. Register, login, and join the TPOWER partner program.",
    footerBlurb: "Official partner platform for TPOWER Casino.",
    footerLegal: "TPOWER Casino Partner Platform",
    copyright: "All rights reserved.",
  },
  cta: {
    register: "Register",
    login: "Login",
    registerNow: "Register Now",
    learnMore: "Learn More",
    contactSupport: "Contact Support",
    alreadyPartner: "Already a partner? Login",
    noAccount: "Don't have a partner account? Register",
    becomePartner: "Become A Partner",
    exploreProgram: "Explore Partner Program",
    viewResources: "View Resources",
    forgotPassword: "Forgot Password?",
  },
  nav: {
    program: "Program",
    partners: "Partners",
    resources: "Resources",
    support: "Support",
  },
  mega: {
    program: "Program",
    partners: "Partners",
    resources: "Resources",
    support: "Support",
    partnerProgram: "Partner Program",
    whyTpower: "Why TPOWER",
    benefits: "Benefits",
    commission: "Commission",
    about: "About TPOWER Partner",
    partnerTypes: "Partner Types",
    affiliateProgram: "Affiliate Program",
    agentProgram: "Agent Program",
    howItWorks: "How It Works",
    marketingResources: "Marketing Resources",
    promotionalMaterials: "Promotional Materials",
    partnerTools: "Partner Tools",
    insights: "Partner Insights",
    news: "News",
    faq: "FAQ",
    partnerSupport: "Partner Support",
    contact: "Contact",
    login: "Login",
    register: "Register Now",
  },
  footer: {
    program: "Program",
    partners: "Partners",
    resources: "Resources",
    support: "Support",
    legal: "Legal",
    partnerProgram: "Partner Program",
    whyTpower: "Why TPOWER",
    benefits: "Benefits",
    commission: "Commission",
    partnerTypes: "Partner Types",
    affiliateProgram: "Affiliate Program",
    agentProgram: "Agent Program",
    howItWorks: "How It Works",
    marketingResources: "Marketing Resources",
    promotionalMaterials: "Promotional Materials",
    partnerTools: "Partner Tools",
    insights: "Partner Insights",
    news: "News",
    faq: "FAQ",
    partnerSupport: "Partner Support",
    contact: "Contact",
    register: "Register",
    login: "Login",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    responsibleGaming: "Responsible Gaming",
    compliance: "Compliance",
    affiliateGuidelines: "Affiliate Guidelines",
    contentGuidelines: "Content Guidelines",
  },
  forms: {
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    partnerType: "Partner Type",
    selectType: "Select type",
    affiliate: "Affiliate Partner",
    website: "Website Owner",
    content: "Content Creator",
    social: "Social Media Partner",
    traffic: "Traffic Partner",
    agent: "Agent",
    websiteSource: "Website / Traffic Source",
    country: "Country / Market",
    message: "Message",
    password: "Password",
    submitRegister: "Register Now",
    submitLogin: "Login",
    submitContact: "Send Message",
    applicationSubmitted: "Application Submitted",
    applicationThanks: "Our team will review your registration and contact you shortly.",
    welcomeBack: "Welcome Back, Partner",
    loginSubtitle: "Sign in to your TPOWER Partner account.",
    registerSubtitle:
      "Register through the official TPOWER Partner platform and join the TPOWER casino partner ecosystem.",
    becomePartner: "Become A TPOWER Partner",
    contactTitle: "Contact Partner Support",
    contactSubtitle: "Reach the TPOWER Partner team for program and account questions.",
    contactSent: "Message Sent",
    contactThanks: "Thank you. Our partner support team will respond as soon as possible.",
    portalLabel: "TPOWER Partner Portal",
    officialPlatform: "Official TPOWER Partner Platform",
    loading: "Submitting…",
    errorRequired: "This field is required.",
  },
  home: {} as import("@/content/en/home").HomeContent,
};
