import type { UiDictionary } from "@/content/types";

export const ui: UiDictionary = {
  site: {
    name: "TPOWER 合作伙伴",
    tagline: "TPOWER 官方合作伙伴平台",
    description:
      "TPOWER 合作伙伴是 TPOWER 在线赌场的官方合作伙伴与联盟推广平台。注册、登录并加入 TPOWER 合作伙伴计划。",
    footerBlurb: "TPOWER 在线赌场官方合作伙伴平台。",
    footerLegal: "TPOWER 赌场合作伙伴平台",
    copyright: "版权所有。",
  },
  cta: {
    register: "注册",
    login: "登录",
    registerNow: "立即注册",
    learnMore: "了解更多",
    contactSupport: "联系支持",
    alreadyPartner: "已是合作伙伴？登录",
    noAccount: "还没有合作伙伴账户？注册",
    becomePartner: "成为合作伙伴",
    exploreProgram: "探索合作伙伴计划",
    viewResources: "查看资源",
    forgotPassword: "忘记密码？",
  },
  nav: {
    program: "计划",
    partners: "合作伙伴",
    resources: "资源",
    support: "支持",
  },
  mega: {
    program: "计划",
    partners: "合作伙伴",
    resources: "资源",
    support: "支持",
    partnerProgram: "合作伙伴计划",
    whyTpower: "为何选择 TPOWER",
    benefits: "合作优势",
    commission: "佣金机制",
    about: "关于 TPOWER 合作伙伴",
    partnerTypes: "合作伙伴类型",
    affiliateProgram: "联盟推广计划",
    agentProgram: "代理计划",
    howItWorks: "合作流程",
    marketingResources: "营销资源",
    promotionalMaterials: "推广素材",
    partnerTools: "合作伙伴工具",
    insights: "合作伙伴洞察",
    news: "新闻动态",
    faq: "常见问题",
    partnerSupport: "合作伙伴支持",
    contact: "联系我们",
    login: "登录",
    register: "立即注册",
  },
  footer: {
    program: "计划",
    partners: "合作伙伴",
    resources: "资源",
    support: "支持",
    legal: "法律",
    partnerProgram: "合作伙伴计划",
    whyTpower: "为何选择 TPOWER",
    benefits: "合作优势",
    commission: "佣金机制",
    partnerTypes: "合作伙伴类型",
    affiliateProgram: "联盟推广计划",
    agentProgram: "代理计划",
    howItWorks: "合作流程",
    marketingResources: "营销资源",
    promotionalMaterials: "推广素材",
    partnerTools: "合作伙伴工具",
    insights: "合作伙伴洞察",
    news: "新闻动态",
    faq: "常见问题",
    partnerSupport: "合作伙伴支持",
    contact: "联系我们",
    register: "注册",
    login: "登录",
    terms: "条款与条件",
    privacy: "隐私政策",
    responsibleGaming: "负责任博彩",
    compliance: "合规",
    affiliateGuidelines: "联盟推广指南",
    contentGuidelines: "内容指南",
  },
  forms: {
    firstName: "名",
    lastName: "姓",
    email: "电子邮箱",
    partnerType: "合作伙伴类型",
    selectType: "请选择类型",
    affiliate: "联盟推广合作伙伴",
    website: "网站主",
    content: "内容创作者",
    social: "社交媒体合作伙伴",
    traffic: "流量合作伙伴",
    agent: "代理",
    websiteSource: "网站 / 流量来源",
    country: "国家 / 市场",
    message: "留言",
    password: "密码",
    submitRegister: "立即注册",
    submitLogin: "登录",
    submitContact: "发送留言",
    applicationSubmitted: "申请已提交",
    applicationThanks: "我们的团队将审核您的注册申请并尽快与您联系。",
    welcomeBack: "欢迎回来，合作伙伴",
    loginSubtitle: "登录以访问您的 TPOWER 合作伙伴账户。",
    registerSubtitle: "通过 TPOWER 官方合作伙伴平台提交申请，开启合作伙伴审核流程。",
    becomePartner: "成为 TPOWER 合作伙伴",
    contactTitle: "联系合作伙伴支持",
    contactSubtitle: "如有计划或账户相关问题，请联系 TPOWER 合作伙伴团队。",
    contactSent: "留言已发送",
    contactThanks: "感谢您的留言，合作伙伴支持团队将尽快回复。",
    portalLabel: "TPOWER 合作伙伴平台",
    officialPlatform: "TPOWER 官方合作伙伴平台",
    loading: "提交中…",
    errorRequired: "此字段为必填项。",
  },
  home: {} as import("@/content/en/home").HomeContent,
};
