import type { UiDictionary } from "@/content/types";

export const ui: UiDictionary = {
  site: {
    name: "TPOWER",
    tagline: "TPOWER 官方合作伙伴网站",
    description:
      "通过官方合作伙伴网站访问 TPOWER 在线赌场。注册 TPOWER 账户、登录、探索游戏、查看优惠并获取支持。",
    footerBlurb: "TPOWER 在线赌场官方合作伙伴网站，提供注册、登录与支持入口。",
    footerLegal: "TPOWER 官方合作伙伴网站",
    copyright: "保留所有权利。",
  },
  cta: {
    register: "注册",
    login: "登录",
    registerNow: "立即注册",
    learnMore: "了解更多",
    contactSupport: "联系支持",
    alreadyAccount: "已有账户？登录",
    noAccount: "还没有账户？注册",
    exploreGames: "探索游戏",
    viewPromotions: "查看优惠",
    forgotPassword: "忘记密码？",
  },
  nav: {
    home: "首页",
    games: "游戏",
    promotions: "优惠",
    payment: "支付",
    faq: "常见问题",
    support: "支持",
  },
  footer: {
    explore: "探索",
    account: "账户",
    help: "帮助",
    legal: "法律",
    home: "首页",
    games: "游戏",
    promotions: "优惠",
    payment: "支付",
    faq: "常见问题",
    support: "支持",
    about: "关于",
    contact: "联系我们",
    register: "注册",
    login: "登录",
    terms: "条款与条件",
    privacy: "隐私政策",
    responsibleGaming: "负责任博彩",
    whyTpower: "为何选择 TPOWER",
  },
  forms: {
    firstName: "名",
    lastName: "姓",
    email: "电子邮箱",
    message: "留言",
    password: "密码",
    submitRegister: "立即注册",
    submitLogin: "登录",
    submitContact: "发送留言",
    applicationSubmitted: "注册已提交",
    applicationThanks: "感谢您。我们的团队将就您的 TPOWER 账户后续步骤与您联系。",
    welcomeBack: "欢迎回来",
    loginSubtitle: "登录以访问您的 TPOWER 账户。",
    registerSubtitle: "通过本官方合作伙伴网站创建您的 TPOWER 账户。",
    becomePartner: "创建您的 TPOWER 账户",
    contactTitle: "联系支持",
    contactSubtitle: "如有注册、登录或账户相关问题，请联系 TPOWER 支持团队。",
    contactSent: "留言已发送",
    contactThanks: "感谢您的留言，支持团队将尽快回复。",
    portalLabel: "TPOWER 账户入口",
    officialPlatform: "TPOWER 官方合作伙伴网站",
    loading: "提交中…",
    errorRequired: "此字段为必填项。",
  },
  home: {} as import("@/content/zh/home").HomeContent,
};
